# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: New Challenge
site_title: Marcus Nyqvist, New Challenge
email: marcus@newchallenge.se
phone: 0735-83 33 29
phone_short: "+46735833329"
description: New Challenge erbjuder idrottspsykologisk rådgivning och föreläsningar.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://newchallenge.se" # the base hostname & protocol for your site, e.g. http://example.com
instagram_access_token: ""

# Build settings
host: 0.0.0.0
markdown: kramdown
# theme: minima
plugins:
  - jekyll-assets
  - jekyll-seo-tag
  - jekyll-sitemap

assets:
  compress:
    css: true
    javascript: true
  prefix: "/assets"
  digest: false
  sources:
    - _assets/img
    - _assets/scss
    - _assets/js
    - _blog_images

language: "sv"
lang: "sv"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
  - dev-docker.sh
  - docker-compose.yml
  - Dockerfile
  - netlify.toml
  - wercker.yml

form:
  success: "/success/"

collections:
  blog:
    output: true

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      image: "/assets/social-share.jpg"
      layout: "page"
  - scope:
      path: "pages" # an empty string here means all files in the project
    values:
      permalink: "/:basename/"
  - scope:
      path: "_blog"
    values:
      image: "/assets/blog_image.jpg"
      layout: "blog"
  - scope:
      path: "admin"
    values:
      sitemap: false
