baseurl: "https://newchallenge.se"
title: "New Challenge"
theme: "newchallenge"
canonifyurls: false
metaDataFormat: "yml"
params:
  index_title: "Välkommen till New Challenge!"
  email: "marcus@newchallenge.se"
  meta_keywords: "marcus, nyqvist, challenge, marcus nyqvist, new challenge, individuell rådgivning, idrottspsykologisk föreläsning"
  meta_description: "New Challenge erbjuder idrottspsykologisk rådgivning och föreläsningar."
  og_image: "/img/newchallenge-social-share.png"
  og_image_width: "1238"
  og_image_height: "648"
