baseurl: ""
title: "New Challenge"
theme: "newchallenge"
canonifyurls: false
metaDataFormat: "yml"
params:
  index_title: "Välkommen till New Challenge!"
  email: "marcus@newchallenge.se"
  mandrill: "ZIVFR36MlOEJhv5hN3d6ug"
  meta_keywords: "marcus, nyqvist, challenge, marcus nyqvist, new challenge, individuell rådgivning, idrottspsykologisk föreläsning"
  meta_description: "New Challenge erbjuder idrottspsykologisk rådgivning och föreläsningar."
