baseurl: "http://calvinmcgee.github.io/newchallenge/"
title: "Marcus Nyqvist, New Challenge"
theme: "newchallenge"
canonifyurls: true
metaDataFormat: "yml"
publishDir: "public_dev"
params:
  company: "New Challenge"
  index_h1: "Välkommen till New Challenge!"
  index_title: "Idrottspsykologisk rådgivning med Marcus Nyqvist, New Challenge"
  email: "marcus@newchallenge.se"
  dev: true
  meta_keywords: "marcus, nyqvist, challenge, marcus nyqvist, new challenge, individuell rådgivning, idrottspsykologisk föreläsning"
  meta_description: "New Challenge erbjuder idrottspsykologisk rådgivning och föreläsningar."
  og_image: "img/newchallenge-social-share.png"
  og_image_width: "1238"
  og_image_height: "648"
