version: '3'

services:
  jekyll:
    build: .
    command: bundle exec jekyll serve --config _config.yml,_dev.yml --host 0.0.0.0 --port 4000 -w
    ports:
      - 4000:4000
    volumes:
      - .:/app
