version: '3'

services:
  jekyll:
    build: .
    environment:
      INSTAGRAM_CONFIG_URL: https://vziovhnlhi.execute-api.eu-north-1.amazonaws.com/production/instagram
    command: bash -c "rake; bundle exec jekyll serve --config _config.yml,_dev.yml --host 0.0.0.0 --port 4000 -w"
    ports:
      - 4000:4000
    volumes:
      - .:/app
