[build]
  command = "jekyll build --config _config.yml"
  publish = "_site"

[context.develop]
  command = "jekyll build --config _config.yml,_dev.yml"

[[redirects]]
  from = "/event/*"
  to = "/"

[[redirects]]
  from = "/om-foretaget/sponsorer/"
  to = "/"

[[redirects]]
  from = "/kontakt/"
  to = "/"
