[build]
  command = "jekyll build --config _config.yml"
  publish = "_site"

[[redirects]]
  from = "/event/*"
  to = "/"

[[redirects]]
  from = "/om-foretaget/sponsorer/"
  to = "/"

[[redirects]]
  from = "/kontakt/"
  to = "/"
