[build]
  command = "rake;jekyll build --config _config.yml,_instagram.yml"
  publish = "_site"

[context.develop]
  command = "rake;jekyll build --config _config.yml,_dev.yml,_instagram.yml"

[context.test-blogs]
  command = "rake;jekyll build --config _config.yml,_dev.yml,_test-blogs.yml,_instagram.yml"

[[redirects]]
  from = "/event/*"
  to = "/"

[[redirects]]
  from = "/om-foretaget/sponsorer/"
  to = "/"

[[redirects]]
  from = "/kontakt/"
  to = "/"
