contact: |
  Kontakta Marcus Nyqvist om du har frågor kring rådgivning eller föreläsningar.

  Skicka en intresseanmälan här på hemsidan direkt eller till [marcus@newchallenge.se](mailto:marcus@newchallenge.se).

  Eller ring på [0735-83 33 29](tel:+46735833329).
footer_text: |
  Idrottpsykologisk rådgivning för individ och grupp.  
  Föreläsning kring psykologiska faktorer som påverkar välmående och prestation.
instagram:
  account: https://instagram.com/marcus_newchallenge/
  pictures: 6
