backend:
  name: git-gateway
  branch: jekyll # Branch to update (optional; defaults to master)
media_folder: "uploads" # Media files will be stored in the repo under images/uploads
collections: # A list of collections the CMS should be able to edit
  # POSTS
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - label: "Author"
        name: "author"
        widget: "select"
        options:
          - { label: "Dan Urbanowicz", value: "dan_urbanowicz" }
          - { label: "John Doe", value: "john_doe" }
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Categories", name: "categories", widget: "string", required: false}
    # PAGES
  - name: "page"
    label: "Page"
    folder: "pages"
    sort: "title:asc"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Section", name: "section", widget: "hidden", default: "{{name}}"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "home"
    label: "Home"
    files:
      - label: "Home Page"
        name: "home"
        file: "_data/home.yml"
        fields:
          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "markdown"
              - label: "Body"
                name: body
                widget: "markdown"
          - label: "Feature"
            name: "feature"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "markdown"
              - label: "Sections"
                name: "sections"
                widget: "list"
                fields:
                - label: "Title"
                  name: "title"
                  widget: "markdown"
                - label: "Icon"
                  name: "icon"
                  widget: "string"
                - label: "Body"
                  name: "body"
                  widget: "markdown"
